# Generated by Django 2.2.6 on 2020-03-05 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroSalud',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('departamento', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('emailSupervisor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('turno', models.CharField(max_length=25)),
                ('centroSalud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agenda.CentroSalud')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('ranking', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=50)),
                ('apellio', models.CharField(max_length=50)),
                ('ci', models.IntegerField(primary_key=True, serialize=False)),
                ('nroCaja', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=60)),
                ('password', models.IntegerField()),
                ('guardia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agenda.Guardia')),
            ],
        ),
    ]
