# Generated by Django 2.2.6 on 2020-03-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0002_medico_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='guardia',
        ),
    ]
