# Generated by Django 2.2.6 on 2020-03-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0003_remove_medico_guardia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='apellio',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='email',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='password',
        ),
    ]
