# Generated by Django 2.2.6 on 2020-03-09 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0005_auto_20200308_2125'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='guardia',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='guardia',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Agenda.Medico'),
        ),
    ]
