# Generated by Django 2.2.6 on 2020-03-13 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0006_auto_20200313_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardia',
            name='usuario',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
