# Generated by Django 2.2.6 on 2020-03-13 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0008_auto_20200310_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='guardia',
            name='fecha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Agenda.Fecha'),
        ),
    ]
