# Generated by Django 2.2.6 on 2020-03-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0009_auto_20200313_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardia',
            name='fecha',
            field=models.DateField(),
        ),
    ]
