# Generated by Django 2.2.6 on 2020-03-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0010_auto_20200313_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='fecha',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fecha',
            name='fecha',
            field=models.DateField(),
        ),
    ]
