# Generated by Django 2.2.6 on 2020-03-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0011_auto_20200313_0856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fecha',
        ),
    ]
