# Generated by Django 2.2.6 on 2020-03-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0007_auto_20200313_0919'),
        ('Agenda', '0013_fecha'),
    ]

    operations = [
    ]
