# Generated by Django 2.2.6 on 2020-03-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0014_merge_20200313_0928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fecha',
        ),
    ]
